# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wayne's Blog
email: huhuanfeng198@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  工作近8年时间,目前在南太平洋小国新西兰工作生活,在一家不算小的小公司从事Java开发工作,不久前拿到新西兰的Resident Visa。
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: 356173471
#github_username:  Wayne-Hu

# Build settings
markdown: kramdown
